services:
  ecal:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    # privileged: true
    command: sleep infinity
