version: '3.8'

services:
  ecal:
    build:
      context: .
      dockerfile: Dockerfile

    # devices:
    #   - "/dev/video0:/dev/video0"

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    